package io.mend.demo.config;

import org.kie.api.KieBase;
import org.kie.api.KieBaseConfiguration;
import org.kie.api.KieServices;
import org.kie.api.conf.EventProcessingOption;
import org.kie.api.runtime.KieContainer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Drools configuration that uses the classes generated by the Kogito Maven plugin.
 */
@Configuration
public class DroolsConfig {

	private final KieServices kieServices = KieServices.get();

	@Bean
	public KieContainer kieContainer() {
		// Get the KieContainer from the KieServices
		// This will automatically find the generated classes on the classpath
		return kieServices.newKieClasspathContainer();
	}

	@Bean
	public KieBase kieBase() {
		KieBaseConfiguration kieBaseConfig = kieServices.newKieBaseConfiguration();
		kieBaseConfig.setOption(EventProcessingOption.STREAM);
		return kieContainer().newKieBase(kieBaseConfig);
	}

}
