package io.mend.demo.config;

import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

/**
 * Drools configuration that uses the classes generated by the Kogito Maven plugin.
 */
@Configuration
@ComponentScan(basePackages = { "org.kie.kogito.**", "org.drools.**" })
public class DroolsConfig {
}
